version: "3.7"

services:
    nginx-proxy:
      container_name: nginx-proxy
      image: jwilder/nginx-proxy:latest
      restart: always
      ports:
          - "80:80"
          - "443:443"
      volumes:
          - conf:/etc/nginx/conf.d
          - ./etc/nginx/my-proxy.conf:/etc/nginx/conf.d/my-proxy.conf
          - vhost:/etc/nginx/vhost.d
          - ${ROOT_PATH}:/usr/share/nginx/html
          - dhparam:/etc/nginx/dhparam
          - certs:/etc/nginx/certs
          - /var/run/docker.sock:/tmp/docker.sock:ro
      labels:
          - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
      networks:
          services-network:
              aliases:
              - nginx-proxy

    letsencrypt:
      container_name: nginx-proxy-certificates
      image: jrcs/letsencrypt-nginx-proxy-companion:latest
      depends_on:
          - nginx-proxy
      environment:
          - DEFAULT_EMAIL=javifloresp@gmail.com
      volumes:
          - conf:/etc/nginx/conf.d
          - vhost:/etc/nginx/vhost.d
          - ${ROOT_PATH}:/usr/share/nginx/html
          - dhparam:/etc/nginx/dhparam
          - certs:/etc/nginx/certs
          - /var/run/docker.sock:/var/run/docker.sock:ro
      networks:
          services-network:
              aliases:
              - letsencrypt

    nginx:
      container_name: nginx
      build: ./etc/nginx
      image: crowdfunding/nginx:latest
      expose:
          - 80
      volumes:
          - ${ROOT_PATH}:/var/www/vhosts
          - ./etc/nginx/nginx-gzip.conf:/etc/nginx/conf.d/000-nginx-gzip.conf
          - ./etc/nginx/nginx-log-format.conf:/etc/nginx/conf.d/000-nginx-log-format.conf
          - ./etc/nginx/site.conf:/etc/nginx/conf.d/default.conf
      environment:
          - VIRTUAL_HOST=${DOMAINS}
          - LETSENCRYPT_HOST=${DOMAINS_SSL}
      links:
          - php
      networks:
          services-network:
              aliases:
              - nginx

    dbserver:
        container_name: mysql-crowdfunding
        image: mysql:latest
        ports:
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password --skip-symbolic-links
        restart: always
        volumes:
            - ./etc/mysql:/etc/mysql/conf.d
            - ./data-initdb.d:/docker-entrypoint-initdb.d
            - type: bind
              source: ./data
              target: /var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${PASSWORD}
            MYSQL_DATABASE: ${DATABASE}
        networks:
            services-network:
                aliases:
                - dbserver

    php:
        container_name: php
        build: ./etc/php
        image: crowdfunding/php7.4-fpm:latest
        expose:
          - 5001
        volumes:
            - ${ROOT_PATH}:/var/www/vhosts
            - ./etc/php/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
            - ./etc/custom-php.ini:/usr/local/etc/php/conf.d/custom-php.ini
        links:
            - dbserver
        networks:
            services-network:
                aliases:
                - php
    dashboard:
      container_name: dashboard
      image: portainer/portainer
      expose:
        - 9000
      command: -H unix:///var/run/docker.sock
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - portainer_data:/data
      environment:
        - VIRTUAL_HOST=${DASHBOARD}
        - VIRTUAL_PORT=9000
        - LETSENCRYPT_HOST=${DOMAINS_SSL}
      networks:
          services-network:
              aliases:
              - dashboard

volumes:
    conf:
    vhost:
    html:
    dhparam:
    certs:
    portainer_data:

networks:
   services-network:
     name: services-network
     driver: bridge